---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 74170.
--- DateTime: 2019/10/21 10:26
---Lua I/O 库用于读取和处理文件。分为简单模式（和C一样）、完全模式。
--
--简单模式（simple model）拥有一个当前输入文件和一个当前输出文件，并且提供针对这些文件相关的操作。
--完全模式（complete model） 使用外部的文件句柄来实现。它以一种面对对象的形式，将所有的文件操作定义为文件句柄的方法
--简单模式在做一些简单的文件操作时较为合适。但是在进行一些高级的文件操作的时候，简单模式就显得力不从心。例如同时读取多个文件这样的操作，使用完全模式则较为合适。
--
--打开文件操作语句如下：
--https://www.runoob.com/lua/lua-file-io.html



-- 简单模式  简单模式使用标准的 I/O 或使用一个当前输入文件和一个当前输出文件。
-- 以只读方式打开  不支持中文文件名
file = io.open(string.format('C:/Users/74170/Desktop/1.txt'), 'r')

--设置输入文件为file
io.input(file)
-- 读取第一行
print(io.read())

--关闭当前文件
io.close(file)

-------------------------------------------

--以附加方式打开
file = io.open('module.lua', 'a+')

--设置默认输入文件
io.output(file)

--在最后一行添加注释
io.write("-- Io end")

--关闭文件
io.close()

-- 完全模式
--通常我们需要在同一时间处理多个文件。我们需要使用 file:function_name 来代替 io.function_name 方法。以下实例演示了如何同时处理同一个文件:

-- 以只读方式打开  不支持中文文件名
file = io.open('C:/Users/74170/Desktop/1.txt', 'a+')

--print(file:read())

file:write("Lua io end..")

--关闭当前文件
file:close()

for line in io.lines('C:/Users/74170/Desktop/1.txt') do
    print(line)
end