---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 74170.
--- DateTime: 2019/10/23 16:14
--- Lua面向对象

--. 与 : 的区别在于使用 : 定义的函数隐含 self 参数，使用 : 调用函数会自动传入 table 至 self 参数

-- 定义元类
Obj = { name = 'zm', age = 23, sex = '男' }

-- 定义一个派生方法
function Obj:new(o)
    o = o or {}
    setmetatable(o, self)     -- self 是对象本身
    self.__index = self       -- 拷贝索引至当前对象
    return o
end

function Obj:getSelf()
    return self
end
-- 创建对象
myObj = Obj:new()

--通过索引访问
print(myObj.name)

-- 测试self
print(Obj:getSelf())

obj2 =  Obj:getSelf()

print(obj2)

print(Obj:new().name)