---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 74170.
--- DateTime: 2019/10/18 16:00
---

fruits = { 12, 22, 33, 1 }
print("排序前")
for k, v in ipairs(fruits) do
    print(k, v)
end

table.sort(fruits)
print("排序后")
for k, v in ipairs(fruits) do
    print(k, v)
end

-- table操作
-- 在末尾插入
table.insert(fruits, "mango")
print("索引为 4 的元素为 ", fruits[4])

--在索引为 2 的键处插入
table.insert(fruits, 2, "grapes")
print("索引为 2 的元素为 ", fruits[2])

print("最后一个元素为 ", fruits[5])
table.remove(fruits)
print("移除后最后一个元素为 ", fruits[5])

list3 = { "1", "2", "3" }
print(table.concat(list3))
fruits = { "banana", "orange", "apple" }

--在末尾插入
table.insert(fruits, "mango")
print("索引为 4 的元素为 ", fruits[4])

print(table.unpack(fruits))
